export const keys = {
  publicKey: `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDzVpDsej3uvjQxZmDBEWOqHnlh
5kzQoUFnOxZNYHdHzqnwVNe9t22yKlpKVgT+QvAO7nvxJ/neN+Ccsd+bhWPrrWBN
yskMPPscNJ+o6OMw8vCFbIqF42IN34u+9Pmozv2mlDc3oxfKFaPiMjv3sKC3/Vfr
fkfsED9zlt7dV5SAqQIDAQAB
-----END PUBLIC KEY-----
`,
  privateKey: `-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQDzVpDsej3uvjQxZmDBEWOqHnlh5kzQoUFnOxZNYHdHzqnwVNe9
t22yKlpKVgT+QvAO7nvxJ/neN+Ccsd+bhWPrrWBNyskMPPscNJ+o6OMw8vCFbIqF
42IN34u+9Pmozv2mlDc3oxfKFaPiMjv3sKC3/VfrfkfsED9zlt7dV5SAqQIDAQAB
AoGBAMntW/XguuQTElysCD4un/Xbs/55jeTS6+MuNSOgmVsNNBgrT5wvSug+HQ7y
stIL2gmJ/W/xLHgrBkkBkf0MhAzAZhZ/c7PQ1qzLJkUl+yp31HkEcAPoOIqOb58D
nwYPA23btDY7xwlOhOBVlYueZo5JarDB/xlAFqRVhnk+Cn8BAkEA+KrUnqYt93bE
1Jt7jqQNdWdCMycNjGjK2KuwoIH6PxD16IBadi+7H/t0xRoxIUc+DrZg4bafMar3
3kaq6HoPjQJBAPqDgZTtrfjyPSgKunAC9XVBogFi1AlDlf4XMxGr1JstZsoh4ReH
jeqrmJvM43Z8Iyr+DqgXdf73bZRkT1WNsI0CQQC3XwI7m7/55JNxVNbgcQmbsfGX
Vw0epYgwDyvIsRCgwRkVwtDypnAPPZb2YkIokCirIMKAr/Lk5XazatlNZfVhAkAA
yJqGKbwqlC9myanNoeS8qijkkjeRk9mLQu1Q99WhaqHwrexzU2Q5QLIogpqPi1Hc
15CaLACdfI6mMS4iWWAdAkAQzU/b7jIwGgbJfqwelcGJSz3l7ncDqiQhUya3d3+n
amSgiMW5eP1C3dBuZTGtjdfxuUEDdkAkH9bNyrs6TWNi
-----END RSA PRIVATE KEY-----
`
};